import { readFile } from "node:fs/promises";

import { createKeyPairSignerFromBytes } from "@solana/kit";

const keypairPath = process.env.STRYKE_WALLET_KEYPAIR_PATH;
if (!keypairPath) throw new Error("STRYKE_WALLET_KEYPAIR_PATH is required");

let contents;
try {
  contents = await readFile(keypairPath, "utf8");
} catch {
  throw new Error(`Cannot read STRYKE_WALLET_KEYPAIR_PATH at ${keypairPath}. Create it with solana-keygen or correct the path in .env`);
}

let stored;
try {
  stored = JSON.parse(contents);
} catch {
  throw new Error(`STRYKE_WALLET_KEYPAIR_PATH at ${keypairPath} is not valid JSON. Regenerate the dedicated trading keypair with solana-keygen`);
}
if (!Array.isArray(stored) || stored.length !== 64 || stored.some((byte) => !Number.isInteger(byte))) {
  throw new Error(`STRYKE_WALLET_KEYPAIR_PATH at ${keypairPath} must contain a 64-byte JSON array generated by solana-keygen`);
}

export default await createKeyPairSignerFromBytes(Uint8Array.from(stored));
